import sys,json,uuid,base64
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from dgp_demo.engine import Engine,check,GRAPH
from dgp_demo.contracts import VERSION
root=Path(__file__).resolve().parents[1]/'examples'
e=Engine();index=[]
def save(name,kind,obj):
 if kind:check(kind,obj)
 (root/name).write_text(json.dumps(obj,indent=2,ensure_ascii=False)+'\n')
 index.append({'file':name,'schema':kind})
f=e.frame('thread-42')
d=f['decisions'][0]
a={'dgp':VERSION,'assessment_id':'a-example-retry','frame_id':f['frame_id'],'decision_id':d['decision_id'],
   'mode':'live','resolver':{'kind':'rule','provider':'local-demo','model':'fixture-not-jev'},
   'result':{'status':'answered','answer':{'choice':'retry','input':{}}}}
stored=e.assess(a,'agent-example')
c={'dgp':VERSION,'frame_id':f['frame_id'],'decision_id':d['decision_id'],'assessment_id':a['assessment_id']}
r=e.commit(c,'agent-example','agent','example-retry-key')
save('01-manifest.json','Manifest',e.manifest())
save('02-frame-next.json','Frame',f)
save('03-assessment-request.json','AssessmentRequest',a)
save('04-assessment-record.json','Assessment',stored)
save('05-commit-request.json','CommitRequest',c)
save('06-receipt.json','Receipt',r)
save('07-next-frame.json','Frame',e.frame('thread-42'))
save('08-frame-horizon.json','Frame',e.frame('thread-73','horizon',2))
save('09-frame-full.json','Frame',e.frame('thread-73','full'))
save('10-static-graph.json','Graph',GRAPH)
f=e.frame('thread-73');d=next(d for d in f['decisions'] if d['node_id']=='attach_image')
image={'mime_type':'image/png','data_base64':'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l6cAAAAASUVORK5CYII='}
a={'dgp':VERSION,'assessment_id':'a-example-image','frame_id':f['frame_id'],'decision_id':d['decision_id'],
   'mode':'live','resolver':{'kind':'human'},'result':{'status':'answered','answer':{'value':image}}}
e.assess(a,'human-example');e.commit({'dgp':VERSION,'frame_id':f['frame_id'],'decision_id':d['decision_id'],'assessment_id':a['assessment_id']},'human-example','human','image-key')
save('11-frame-image.json','Frame',e.frame('thread-73'))
(root/'fixture-index.json').write_text(json.dumps(index,indent=2)+'\n')
(root/'README.md').write_text('''# Protocol fixtures\n\nThese JSON records were generated by the included application and validated against `schemas/dgp.schema.json`. The first transition is mutually linked from `02-frame-next.json` through `07-next-frame.json`. Use `Idempotency-Key: example-retry-key` when replaying the illustrative commit.\n\nThe records belong to a temporary synthetic database, not your running demo. Read fresh frame IDs when driving your own server. `fixture-index.json` lists the JSON Schema definition for each record.\n\nThe static/horizon/full files illustrate template disclosure. The image frame points to a blob in that temporary fixture database, not a live public URL; its purpose is to show the transport representation.\n''')
e.close();print(f'Validated {len(index)} fixture records.')
